version: '3.4'
services:
  postgres:
    image: postgres:13.0
    container_name: ${DATABASE_NAME}.postgres
    networks:
      - sad_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/database/init.sql:/var/lib/docker/volumes/sad-hotel/_data/init.sql
networks:
  sad_network:
    external:
      name: sad_network

